class Viewport:
    def set_canvas_size(self, width: int, height: int) -> None: ...

    def fit_to_map(self, bounds: MapBounds) -> None: ...

    def map_to_canvas(
        self, map_x: float, map_y: float
    ) -> tuple[float, float]: ...

    def canvas_to_map(
        self, canvas_x: float, canvas_y: float
    ) -> tuple[float, float]: ...
